name: KinD Cluster Setup

on:
  push:
    branches:
    - master  

jobs:
  setup-kind-cluster:
    runs-on: ubuntu-latest  
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up KinD cluster
      uses: engineerd/setup-kind@v0.7.0
      with:
        version: "v0.20.0" 
        config: |
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          nodes:
          - role: control-plane
          - role: worker
          
    - name: Verify cluster
      run: |
        kubectl cluster-info
        kubectl get nodes