  name: KinD Cluster Setup

 on:
  push:
    branches:
      - master  

 jobs:
  setup-kind-cluster:
    runs-on: ubuntu-latest  
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up KinD cluster
      id: kind-setup
      uses: engineerd/setup-kind@v0.7.0
      with:
        version: "v0.20.0" 
        config: |
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          nodes:
          - role: control-plane
          - role: worker
          
    - name: Verify cluster
      run: |
        # Cluster timing information
        echo "=== Cluster Setup Time ==="
        echo "Start time: ${{ steps.kind-setup.outputs.start-time }}"
        echo "Ready time: $(date -u +'%Y-%m-%d %H:%M:%S')"
        
        # Kubernetes version information
        echo -e "\n=== Kubernetes Version ==="
        kubectl version --output=json | jq -r '.serverVersion.gitVersion'
        
        # Node information
        echo -e "\n=== Node Details ==="
        kubectl get nodes -o wide
        echo -e "\nNumber of nodes: $(kubectl get nodes --no-headers | wc -l)"
        
        # Detailed cluster information
        echo -e "\n=== Cluster Details ==="
        kubectl cluster-info
        echo -e "\n=== System Pods ==="
        kubectl get pods -n kube-system --no-headers | wc -l | awk '{print "System pods running:", $1}'