name: Minikube Cluster Setup
on: 
  pull_request:
  push:
    branches: 
      - master

jobs:
  setup-minikube:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/kubectl
        kubectl version --client

    - name: Install Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube

    - name: Start Minikube cluster
      run: |
        minikube start --driver=docker
        minikube status
        echo "Cluster setup complete"

    - name: Get cluster info
      run: |
        echo "=== Cluster Information ==="
        kubectl cluster-info
        echo -n "Number of nodes: "
        kubectl get nodes -o name | wc -l
        echo -n "Kubernetes version: "
        kubectl version --short | grep Server | awk '{print $3}'
        echo "=== Minikube details ==="
        minikube profile list